version: '3'
services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - '.env.docker'
    ports:
      - "5432:5432"
    volumes:
      - './db/:/var/lib/postgresql/data'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'api'
    env_file:
      - '.env.docker'
    ports:
      - '3001:3001'
    depends_on:
      - postgres